-- EMPLOYEE
DELETE FROM EMPLOYEE;
INSERT INTO EMPLOYEE(ID, NAME, DESCRIPTION) VALUES ('1', 'NAME 1','DESCRIPTION 1');
INSERT INTO EMPLOYEE(ID, NAME, DESCRIPTION) VALUES ('2', 'NAME 2','DESCRIPTION 2');
INSERT INTO EMPLOYEE(ID, NAME, DESCRIPTION) VALUES ('3', 'NAME 3','DESCRIPTION 3');
INSERT INTO EMPLOYEE(ID, NAME, DESCRIPTION) VALUES ('4', 'NAME 4','DESCRIPTION 4');
INSERT INTO EMPLOYEE(ID, NAME, DESCRIPTION) VALUES ('5', 'NAME 5','DESCRIPTION 5');